a<-seq(-20,8,7)
a
x=a[length(a):7]
x
x=a[length(a):2]
x
y=c(a[2:round(length(a)/2)],99,a[(round(length(a)/2)+3):length(a)])
y
x=1:10
y=acos(cos(x))
x==y
x=c(sin(15),log(9),log(10,exp(6)),log(100),cos(pi+1), exp(1)^(cos(0)),atan(+Inf))
names(x)=c("sin(15)","log(9)","ln3","lg(100)","cos(pi+1)","e^cos(0)","arctn(+Inf)");
sort(x)
x=seq(-100,90,80)
y=x[(x>90&x<100)|(x>30&x<90&x!=80)]
f=c(rep("mouse",15),rep("rat",10),rep("fly",11))
f=rep(c("mouse","rat","fly"),c(15,10,11))
x=factor(f)
summary(x)
summary(f)
summary(0.1:15)
summary(0.1:15)[5]
dna=factor(rep(c("T","G","C","A"),c(5,7,9,11)))
ratio=summary(dna)/sum(summary(dna))
dna=factor(rep(c("T","G","C","A"),c(5,7,9,11)))
sample(dna)
dna
#sample(dna,size=50,replace=FALSE)
sample(dna,size=50,replace=FALSE)
sample(dna,size=50,replace=TRUE)
sampledna=sample(c("A","T","G","C"),size=100000000,replace=TRUE)
ratio=summary(factor(sampledna))/length(sampledna)
ratio2=summary(factor(dna))/length(dna)
ratio
ratio2
x=1:100
y=10:50
union(x,y)
intersect(x,y)
setdiff(x,y)
setdiff(y,x)
rm(list=ls())
cumsum(1:100)
dna2=sample(c("A","T","G","G","G","C"),size=3826513,replace=TRUE)
ratio=summary(factor(dna2))/length(dna2)
ratio
dna2=sample(c("A","T","G","C"),size=3826513,prob=c(.5/3,.5/3,.5,.5/3),replace=TRUE)
ratio=summary(factor(dna2))/length(dna2)
ratio
iris[iris$Species==c("orrr","jffff"),]
iris[iris$Species==c("setosa","virginica"),]
iris[iris$Species=="setosa"|iris$Species=="virginica",c("Petal.Length","Species")]
summary(factor(iris[(iris$Petal.Length>2&iris$Petal.Length<6),"Species" ]))
my_func=function(p)
{
x=p^4
y=x^2
print("result")
return(c(x,y))
}
my_func(2)
mathses=function(p,q)
{
result=c(p+q,log(p+q,1),exp(p+q))
names(result)=c("summ","log","exp")
return(result)
}
mathses(2,3)
mf=function(p)
{
if(p>0)
{
x=log(p)
return(x)
}
else
{return(NULL)}
}
mf(-1)
myfactorial=function(p)
{if (p>0 & p%%1==0)
{return(gamma(p+1))}
else
{return(NULL)}}
myfactorial(5)
myfactorial=function(p)
{if (p>0 & p%%1==0){return(gamma(p+1))}else{return(NULL)}}
mydistribution = function(x,p)
{if (x>=0&x%%1==0&p<=1&p>0){return(p*(1-p)^x)}else{return(0)}}
mydistribution(3,.4)

